# You can use this file to define resource usage estimates for Infracost to use when calculating
# the cost of usage-based resource, such as AWS S3 or Lambda.
# `infracost breakdown --usage-file infracost-usage.yml [other flags]`
# See https://infracost.io/usage-file/ for docs
version: 0.1
resource_type_default_usage:
  ##
  ## The following usage values apply to each resource of the given type, which is useful when you want to define defaults.
  ## All values are commented-out, you can uncomment resource types and customize as needed.
  ##
  google_logging_project_bucket_config:
    monthly_logging_data_gb: 5.0 # Monthly logging data in GB.
  google_logging_project_sink:
    monthly_logging_data_gb: 5.0 # Monthly logging data in GB.
# resource_usage:
  ##
  ## The following usage values apply to individual resources and override any value defined in the resource_type_default_usage section.
  ## All values are commented-out, you can uncomment resources and customize as needed.
  ##
  # module.projects["logs01"].google_logging_project_bucket_config.cis_2_2_logging_sink[0]:
    # monthly_logging_data_gb: 0.0 # Monthly logging data in GB.
  # module.projects["logs01"].google_logging_project_sink.cis_2_2_logging_sink:
    # monthly_logging_data_gb: 0.0 # Monthly logging data in GB.
