name: Sandbox

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  global_infra:
    name: "Global"
    uses: osinfra-io/github-terraform-called-workflows/.github/workflows/gcp-plan-and-apply.yml@main
    with:
      checkout_ref: ${{ github.ref }}
      github_environment: "Sandbox Infrastructure: Global"
      service_account: plt-lz-audit-github@ptl-lz-terraform-tf91-sb.iam.gserviceaccount.com
      terraform_plan_args: -var-file=tfvars/sb.tfvars
      terraform_state_bucket: plt-lz-audit-2c8b-sb
      terraform_version: 1.3.9
      terraform_workspace: global-sandbox
      working_directory: global/infra
      workload_identity_provider: projects/746490462722/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      terraform_plan_secret_args: -var="billing_account=${{ secrets.BILLING_ACCOUNT }}"
